mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")),
]

polls/urls.py
from django.urls import path
from . import views

app_name = "polls" # this will namespace the URL to the polls app
urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    # ex: /polls/5/
    # the 'name' value as called by the {% url %} template tag
    path("<int:question_id>", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
    # Use the generic Class-based IndexView instead of the index view function
    # path("", views.IndexView.as_view(), name="index"),
    # Use the generic Class-based DetailView instead of the detail view function
    # path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # Use the generic Class-based ResultsView instead of the results view function
    # path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    # returns the question text in a query
    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    # returns the choice text in a query
    def __str__(self):
        return self.choice_text

polls/views.py
from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
#from django.views import generic

from .models import Choice, Question

# Class-based view for the index page.
# class IndexView(generic.ListView):
#     template_name = "polls/index.html"
#     context_object_name = "latest_question_list"
    
#     def get_queryset(self):
#         # Return the last five published questions
#         return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]

# # Class-based view for the detail page.
# class DetailView(generic.DetailView):
#     model = Question
#     template_name = "polls/detail.html"

# # Class-based view for the results page.
# class ResultsView(generic.DetailView):
#     model = Question
#     template_name = "polls/results.html"


# These are the function-based views
# This loads a template called polls/index.html and passes it a context.
# The context is a dictionary mapping template variable names to Python objects.
def index(request):
    # latest_question_list = Question.objects.order_by("-pub_date")[:5]
    # Return the last five published questions (not including those set to be published in the future).
    latest_question_list = Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]
    context = {
        "latest_question_list": latest_question_list,
    }
    # Django provides a shortcut for rendering a template. Just use render() function instead of loader and HttpResponse
    return render(request, "polls/index.html", context)

def detail(request, question_id):
    # Do a 404 Error check
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    # There is a get_object_or_404 shortcut to make it easier:
    # Edited to use the pub_date filter to check if the pub_date is in the past
    # and not in a future date
    question = get_object_or_404(Question, pub_date__lte=timezone.now(), pk=question_id)
    context = {
        "question": question,
        "question_id": question_id,
    } 
    return render(request, "polls/detail.html", context)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})

def vote(request, question_id):
    # Get the question object
    question = get_object_or_404(Question, pk=question_id)
    try:
        # Get the choice object from the form data
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form with an error message
        return render( 
            request, "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",    
            },
        )
    else:
        # the F() function is used to directly access the database field without having to do it through the model instance.
        selected_choice.votes = F("votes") + 1
        selected_choice.save()

        # Always return an HttpResponseRedirect after successfully dealing with POST data.
        # This prevents data from being posted twice if a user hits the Back button.
        # The reverse() (a very bad name) function is a shortcut to avoid hardcoding a URL in the view.
        # It takes a view name and returns a URL matching that view.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

polls/templates/polls/detail.html
<html>
<head>
    <title>Poll Question #{{ question_id }}</title>
</head>
<body>
    <!--h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }}</li>
        {% endfor %}
    </ul-->

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %} <!---Cross-Site Request Forgery token for security-->
        <fieldset>
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
</body>

</html>

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Polls</title>
    <link rel="stylesheet" href="{% static "polls/style.css" %}">
</head>
<body>
<!-- latest_question_list is passed in as a context parameter in views.py -->
{% if latest_question_list %}
  <ul>
  {% for question in latest_question_list %}
    <!--li><a href="/polls/{{ question.id }}"-->
    <!-- to prevent use of hard-coded urls, use the URL template tag and refer to the url.py file -->
    <!-- "polls:detail" specified to use the detail url in the "polls" namespace -->
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>No polls are available.</p>
{% endif %}
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Results</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
    {% for choice in question.choice_set.all %}
        <!-- the pluralize function will add an 's' depending on the number given to it (choice.votes) -->
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>